### ISSUE TITLE
Error when loading a model with bones

### ISSUE THREAD

**Issue by Gamesaw-Drew** [rdb/blender-egg-importer#3] opened 2017-03-30 23:46 UTC
Everytime i load a model i get https://gyazo.com/237af123a2a13b0395d05dfc56851a3b

(Sorry for no actual text log as its annoying to copy from blender lul)

**Comment by Gamesaw-Drew** [comment] 2017-03-30 23:49
Using Blender 2.78. Does it not work with this build?

**Comment by rdb** [comment] 2017-03-31 00:25
It would help if you could share the model file you tried to import.

**Comment by Gamesaw-Drew** [comment] 2017-03-31 00:31
Seems to happen with any model

**Comment by rdb** [comment] 2017-03-31 20:56
I really am unable to reproduce it, and I also have Blender 2.78.  The models with bones in the Panda models folder and samples folder seem to work for me.  Could you please attach the model file that fails to import, or e-mail it to me?

**Comment by Gamesaw-Drew** [comment] 2017-04-01 00:06
Alright. I will send you one of the models i tried. its a minecraft character i used as a meme, i actually originally exported it from blender 
[minecraftmemer.zip](https://github.com/rdb/blender-egg-importer/files/887188/minecraftmemer.zip)

**Comment by rdb** [comment] 2017-04-01 06:24
Thanks!  I checked in a fix.  For some reason your model contained nested <Dart> tags; the importer now ignores those.

Let me know if there's more trouble.

**Comment by Gamesaw-Drew** [comment] 2017-04-01 16:10
thanks so much :)

**Comment by Gamesaw-Drew** [comment] 2017-04-01 16:13
While it fixed it for that model, i am still having trouble loading 
[suitA-mod.zip](https://github.com/rdb/blender-egg-importer/files/887776/suitA-mod.zip)

**Comment by rdb** [comment] 2017-04-01 18:53
So it does.  I'm on it.

**Closed** 2017-04-02 14:17 UTC

**Comment by rdb** [comment] 2017-04-02 14:21
The issue was that the character `<Group>` element directly contained geometry.  I've fixed the  egg importer to automatically insert a child object to place the geometry under in this case, which makes the object import correctly.

By the way, it appears to have been exported using an outdated version of bam2egg, since I noticed that there is a useless group at the root, which only older bam2egg versions did.  If you are using bam2egg, I highly recommend you use one that ships with a recent development build of Panda, to make sure that no information is getting lost.

(On a sidenote, this object appears to have bones all over the place, but I think they work correctly nonetheless.  I think it's mostly a cosmetic issue of how the bones are placed and shouldn't affect functionality; the armature can be fixed in edit mode if desired.)
