### ISSUE TITLE
Import fails with <RGBA> populated under each <Vertex> in the <VertexPool>

### ISSUE THREAD

**Issue by Atonement100** [rdb/blender-egg-importer#8] opened 2019-06-10 06:19 UTC
Hi rdb, thank you very much for the plugin & the time you've spent on it! 

I wanted to report an issue I ran into, but was able to work around. 

Essentially, my original .egg fails to import properly. The model appears to be imported as a point in space (pressing `.` will relocate and zoom in, rather than out). Not sure how to retrieve a paste of the stack trace, but here is a photo of it, with an example of the imported model.

(Latest call referring to https://github.com/rdb/blender-egg-importer/blob/master/importer.py#L1043)

<img width="641" alt="blender_2019-06-09_22-50-04" src="https://user-images.githubusercontent.com/8877198/59175270-cf46c900-8b09-11e9-99f6-3e97aee2e0b2.png">

I was able to work around the issue by removing the <RGBA> entry within each <Vertex> in the .egg file, which hopefully helps pin down where the issue comes from.

(Files as txt to let github let me upload)
Original/not working file: [tt_a_chr_dgl_shorts_torso_1000-bad.egg.txt](https://github.com/rdb/blender-egg-importer/files/3270798/tt_a_chr_dgl_shorts_torso_1000-bad.egg.txt)

Working file: [tt_a_chr_dgl_shorts_torso_1000.egg.txt](https://github.com/rdb/blender-egg-importer/files/3270800/tt_a_chr_dgl_shorts_torso_1000.egg.txt)

Once deleting the RGBA's, everything imports as expected (and they don't seem to be important to me for what I'm doing), but figure you may be interested in looking into the issue.

Thanks again for the plugin!

**Comment by rdb** [comment] 2019-09-17 23:03
I haven't looked at the models, but judging by the error message, this appears to be a duplicate of #5.

**Comment by rdb** [comment] 2019-09-17 23:04
Duplicate of #5

**Closed by rdb** 2019-09-17 23:04 UTC

**Comment by rdb** [comment] 2019-09-18 11:08
I think this issue only occurs with certain nightly builds of Blender 2.79c.  If you still encounter this issue with any Blender version, then please go to the Python console and give me the values of `bpy.app.version` and `bpy.app.version_char` for that version.
